; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; 公共配置
[env:nicenano]
platform = nordicnrf52
board = nicenano
framework = arduino
monitor_speed = 115200
lib_deps = 
	https://github.com/nopnop2002/Arduino-LoRa-Ra01S.git
	https://github.com/adafruit/Adafruit_nRF52_Arduino

;发送端固件环境
[env:sender]
;继承公共配置
extends = env:nicenano
build_src_filter = -<*> +<sender/*> +<common/*> ; 只编译sender目录下的文件
;可选：定义宏来区分模式，可在代码中通过 #ifdef SENDER 来判断是否为发送端
build_flags = -D SENDER


;发送端固件环境
[env:receiver]
;继承公共配置
extends = env:nicenano
build_src_filter = -<*> +<receiver/*> +<common/*> ; 只编译receiver目录下的文件
;可选：定义宏来区分模式，可在代码中通过 #ifdef RECEIVER 来判断是否为接收端
build_flags = -D RECEIVER